name: Comment Label Manager

on:
  issue_comment:
    types: [created, edited]

jobs:
# feature-request, bug, duplicate, invalid, not-belong
  auto-create-feature-label:
    if: contain(github.event.comment.body, '/label feature') == true
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "feature-request, enhancement"
  auto-create-bug-label:
    if: contain(github.event.comment.body, '/label bug') == true
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "bug"
  auto-create-duplicate-label:
    if: contain(github.event.comment.body, '/label duplicate') == true
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "duplicate"
  auto-create-invalid-label:
    if: contain(github.event.comment.body, '/label invalid') == true
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "*invalid"
  auto-create-not-belong-label:
    if: contain(github.event.comment.body, '/label not-belong') == true
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "invalid/not-belong"
# wontfix, question, need-discuss
  auto-create-wontfix-label:
    if: contain(github.event.comment.body, '/label wontfix') == true
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "wontfix"
  auto-create-question-label:
    if: contain(github.event.comment.body, '/label question') == true
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "question"
  auto-create-need-discuss-label:
    if: contain(github.event.comment.body, '/label need-discuss') == true
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "need-discuss"